### ISSUE TITLE
Option to add weight of eggs and chicks is not showing

### ISSUE THREAD

**Issue by JeffreyCarbillet** [rix133/flutter_bird_colony#50]
If I go on nest number 2, and click on egg number 2, I can see the weight of the egg.
I created a new nest (number 9), added eggs, but there is no option to add the weight of the eggs.
I also added a new measure, weight at the chick level, I saved it, logged out, and logged in again, but the option is not showing as well.

**Comment by rix133** [comment]
the weight option must be set on the egg level  to see it on eggs however i think it shoud work for birds if it is set as chick but it seems not to work there
