### ISSUE TITLE
Distinguishing egg and chick weight - redirect to bird if egg has ring

### ISSUE THREAD

**Issue by JeffreyCarbillet** [rix133/flutter_bird_colony#59]
It's more a question than an issue I think.

Since I can't download the Excel file to see how the data looks, how does it work with the different weights?

If I add a first egg weight on day 1, another one on day 3, and another one on day 5 for example, then the egg turns into a chick on day 7, with a band number, and status is hatched. If I add the chick weight, it will add a 4th row with the new weight on day 7. But on the final dataset, I guess it's just another column that doesn't make a difference between the weight of when it was an egg or became a chick, right?

If so, should I simply have 2 separate variables, egg weight, and chick weight, that we can measure multiple times, and then easily identify in the final database?

**Comment by rix133** [comment]
> If so, should I simply have 2 separate variables, egg weight, and chick weight, that we can measure multiple times, and then easily identify in the final database?
I think yes. allthoug it is my  idea that once a chick is ringed the button redirects to bird instead of egg and the chick values could be entered there.

**Comment by JeffreyCarbillet** [comment]
Yes, ok. If it works this way then everything should be fine, and no need for the 2 different variables. Thanks!
