### ISSUE TITLE
Only numeric values for numeric variables

### ISSUE THREAD

**Issue by JeffreyCarbillet** [rix133/flutter_bird_colony#66]
Would it be possible to have only the numeric pad available when entering numeric values, such as weight for example? If a variable is set as numeric, that would make it more convenient to have only this option to enter numbers.

**Comment by rix133** [comment]
this works if it is a new measure (ie you are not duplicating an old one) and it is set as numeric in the settings (and the settings is saved!) the second level save button is easy to miss
