### ISSUE TITLE
Option to remove new fields

### ISSUE THREAD

**Issue by JeffreyCarbillet** [rix133/flutter_bird_colony#67]
If someone accidentally adds a new note, or new FID, or any new field, could it be possible to remove it? At least for admin users, for example, to avoid important data being removed randomly. I am now thinking that maybe it can simply be done from the firestore database, at least for now.

**Comment by rix133** [comment]
Once the field does not have any information ie the value is empty the field is deleted meaning that next time you open the nest/egg/bird the value is not shown and removed
