### ISSUE TITLE
Parent data showing only if metal ring

### ISSUE THREAD

**Issue by JeffreyCarbillet** [rix133/flutter_bird_colony#74]
At the moment, the possibility to enter data for parents is available only if a metal ring number is entered and saved. But we will very likely do FID on birds that have plastic rings, so we should be able to enter data for parents that only have plastic rings, and then fill the metal ring and other data at trapping.

**Comment by rix133** [comment]
this is a thing I have thought and I think it will not be available. In this case I suggest you save the bird with a temporary metal eg use plastic as metal and replace with the actual metal once you have caught the bird

**Comment by JeffreyCarbillet** [comment]
Ok, but for now it's not possible to change the metal ring number once it's entered

**Comment by rix133** [comment]
On web it should be

**Comment by JeffreyCarbillet** [comment]
It seems I can't at least, only the plastic one.
![Capturebb](https://github.com/rix133/flutter_bird_colony/assets/99021441/eaa2700a-6177-4692-b790-38a745564762)

**Comment by rix133** [comment]
That's because you are running still the old version

**Comment by JeffreyCarbillet** [comment]
Ok. I don't see an option to update my web version, but you can show me later.
